export default {
  login: 'employee/login',
  getTrainingsWithDate: (ln, start, end, page) =>
    `employee/${ln}/get-trainings?startDate=${start}&endDate=${end}&page=${page}`,
  getTrainings: (ln, page) => `employee/${ln}/get-trainings?page=${page}`,
  getSingleTraining: ln => `employee/${ln}/get-training/`,
  getCertificate: 'employee/my-certificates',
  getSafetyEvaluations: 'employee/get-evaluations',
  getSafetyEvaluationDetail: 'employee/get-evaluation/',
  changePassword: 'employee/change-password',
  subscribeNotification: 'employee/subscribe',
  getNotifications: 'employee/get-notifications',
  clearNotifications: 'employee/clear-notifications',
  readNotifictaion: id => `employee/read-notification/${id}`,
  getResult: 'employee/read',
  updateResult: 'employee/update-result',
  changeStatus: 'employee/acknowledge-violation',
  employeeResult: 'employee/check-result',
  employeeLogout: 'employee/logout',
  getInspections: 'employee/get-inspections',
  addEmployeeInspection: 'employee/add-inspection',
  getInspectionDetails: 'employee/get-inspection',
  deleteAccount: 'employee/delete-user',
};
